# Generated by Django 5.2.8 on 2025-11-30 08:02

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=16)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('market', models.CharField(choices=[('ghana', 'ghana'), ('international', 'international')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'market'], name='market_watc_user_id_2a6d37_idx'), models.Index(django.db.models.functions.text.Lower('symbol'), name='watchlist_symbol_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('symbol'), models.F('user'), models.F('market'), name='uniq_watchlist_user_market_symbol_ci')],
            },
        ),
    ]
